#!/bin/bash
set -e

if [ ! -f idp-private-key.pem ]; then
	openssl req -x509 -new -newkey rsa:2048 -nodes \
	-subj '/C=US/ST=California/L=San Francisco/O=JankyCo/CN=Test Identity Provider' \
	-keyout idp-private-key.pem -out idp-public-cert.pem -days 7300
fi

saml-idp --acs https://localhost:10080/saml2 --aud https://localhost:10080
